src/Entity/Formations.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormationsRepository")
 */
class Formations
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_participant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getNbParticipant(): ?int
    {
        return $this->nb_participant;
    }

    public function setNbParticipant(int $nb_participant): self
    {
        $this->nb_participant = $nb_participant;

        return $this;
    }
}

src/Form/FormationsType.php
<?php

namespace App\Form;

use App\Entity\Formations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut')
            ->add('nb_participant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formations::class,
        ]);
    }
}

src/Controller/FormationsController.php
<?php

namespace App\Controller;

use App\Entity\Formations;
use App\Form\FormationsType;
use App\Repository\FormationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formations")
 */
class FormationsController extends AbstractController
{
    /**
     * @Route("/", name="formations_index", methods={"GET"})
     */
    public function index(FormationsRepository $formationsRepository): Response
    {
        return $this->render('formations/index.html.twig', [
            'formations' => $formationsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formations_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $formation = new Formations();
        $form = $this->createForm(FormationsType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formations_index');
        }

        return $this->render('formations/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formations_show", methods={"GET"})
     */
    public function show(Formations $formation): Response
    {
        return $this->render('formations/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formations_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formations $formation): Response
    {
        $form = $this->createForm(FormationsType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formations_index', [
                'id' => $formation->getId(),
            ]);
        }

        return $this->render('formations/edit.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formations_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formations $formation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formations_index');
    }
}

templates/formations/_delete_form.html.twig
<form method="post" action="{{ path('formations_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/formations/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/formations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formations{% endblock %}

{% block body %}
    <h1>Edit Formations</h1>

    {{ include('formations/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('formations_index') }}">back to list</a>

    {{ include('formations/_delete_form.html.twig') }}
{% endblock %}

templates/formations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations index{% endblock %}

{% block body %}
    <h1>Formations index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut</th>
                <th>Nb_participant</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <td>{{ formation.id }}</td>
                <td>{{ formation.dateDebut ? formation.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ formation.nbParticipant }}</td>
                <td>
                    <a href="{{ path('formations_show', {'id': formation.id}) }}">show</a>
                    <a href="{{ path('formations_edit', {'id': formation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('formations_new') }}">Create new</a>
{% endblock %}

templates/formations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formations{% endblock %}

{% block body %}
    <h1>Create new Formations</h1>

    {{ include('formations/_form.html.twig') }}

    <a href="{{ path('formations_index') }}">back to list</a>
{% endblock %}

templates/formations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations{% endblock %}

{% block body %}
    <h1>Formations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formation.id }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ formation.dateDebut ? formation.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nb_participant</th>
                <td>{{ formation.nbParticipant }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('formations_index') }}">back to list</a>

    <a href="{{ path('formations_edit', {'id': formation.id}) }}">edit</a>

    {{ include('formations/_delete_form.html.twig') }}
{% endblock %}